apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
  {{- include "test-app.labels" . | nindent 4 }}
data:
  configmap_MaxNewSize: {{ .Values.applConfigmap.configmapMaxNewSize | quote }}
  configmap_NewSize: {{ .Values.applConfigmap.configmapNewSize | quote }}
  configmap_Xms: {{ .Values.applConfigmap.configmapXms | quote }}
  configmap_Xmx: {{ .Values.applConfigmap.configmapXmx | quote }}
  configmap_appuser: {{ .Values.applConfigmap.configmapAppuser | quote }}
  configmap_instancehome: {{ .Values.applConfigmap.configmapInstancehome | quote
    }}
  configmap_servertype: {{ .Values.applConfigmap.configmapServertype | quote }}
