apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-app.fullname" . }}
  labels:
  {{- include "test-app.labels" . | nindent 4 }}
data:
  secret_encryptkey: ************************

